FROM node:12-alpine

# create destination directory
RUN mkdir -p /src/app
WORKDIR /src/app

# update and install dependency
RUN apk update && apk upgrade
RUN apk add git

# copy the app, note .dockerignore
COPY . /src/app/
RUN npm install && npm install -g pm2


ENV HOST=0.0.0.0
ENV PORT=5000
ENV API="https://login.ocean99th.com/"
ENV SITE_NAME="Pussywin888"

# build necessary, even if no static files are needed,
# since it builds the server as well
RUN npm run build

# expose 5000 on container
EXPOSE 5000

# set app serving to permissive / assigned
# set app port

# start the app
CMD ["pm2-runtime","npm","--name","app-frontend","--","start"]